//go:build ignore
// +build ignore

package main

import (
	"cmp"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
)

func main() {
	dir := "."
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatal(err)
	}

	re := regexp.MustCompile(`^day(\d+)$`)

	var days []string

	for _, e := range entries {
		if e.IsDir() {
			if re.MatchString(e.Name()) {
				days = append(days, e.Name())
			}
		}
	}

	slices.SortFunc(days, func(a string, b string) int {
		aNum, _ := strconv.Atoi(a[3:])
		bNum, _ := strconv.Atoi(b[3:])
		return cmp.Compare(aNum, bNum)
	})

	f, err := os.Create("autogen_days.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by gen.go; DO NOT EDIT.")
	fmt.Fprintln(f, "package main")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "import (")

	for _, d := range days {
		// Fully-qualified import path (adjust module name accordingly)
		importPath := filepath.ToSlash(filepath.Join("mike-pr.com/AdventOfCode2025", d))
		fmt.Fprintf(f, "\t_ %q\n", importPath)
	}

	fmt.Fprintln(f, ")")
}
